name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    name: Run Test Suite

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd src && python -m pytest ../tests/ -v

  train_and_quantize:
    runs-on: ubuntu-latest
    name: Train Model and Quantize
    needs: test_suite

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        cd src
        python train.py

    - name: Quantize model
      run: |
        cd src
        python quantize.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/
        retention-days: 30

  build_and_test_container:
    runs-on: ubuntu-latest
    name: Build and Test Docker Container
    needs: train_and_quantize

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download model artifacts
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        path: models/

    - name: Build Docker image
      run: |
        docker build -t mlops-linear-regression .

    - name: Test Docker container
      run: |
        docker run --rm mlops-linear-regression